// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADgWnlZOCwESayawiBli7V7YXancYjSnA',
    appId: '1:536304071553:web:9d3d8f35b0235532dd6e80',
    messagingSenderId: '536304071553',
    projectId: 'mash-45080',
    authDomain: 'mash-45080.firebaseapp.com',
    storageBucket: 'mash-45080.firebasestorage.app',
    measurementId: 'G-X5SSG6F2CE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDp-gcfVLg9jLg5rQan7VHx5HSXsxHT2A8',
    appId: '1:536304071553:android:94d589ed680d0fa1dd6e80',
    messagingSenderId: '536304071553',
    projectId: 'mash-45080',
    storageBucket: 'mash-45080.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEBRcCPfwx8Et-upRFp-eiso-mwRMdoN8',
    appId: '1:536304071553:ios:d2fc50d8bf46ba01dd6e80',
    messagingSenderId: '536304071553',
    projectId: 'mash-45080',
    storageBucket: 'mash-45080.firebasestorage.app',
    iosBundleId: 'com.example.insanJamdHawan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEBRcCPfwx8Et-upRFp-eiso-mwRMdoN8',
    appId: '1:536304071553:ios:d2fc50d8bf46ba01dd6e80',
    messagingSenderId: '536304071553',
    projectId: 'mash-45080',
    storageBucket: 'mash-45080.firebasestorage.app',
    iosBundleId: 'com.example.insanJamdHawan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADgWnlZOCwESayawiBli7V7YXancYjSnA',
    appId: '1:536304071553:web:f38f24bbce58ccefdd6e80',
    messagingSenderId: '536304071553',
    projectId: 'mash-45080',
    authDomain: 'mash-45080.firebaseapp.com',
    storageBucket: 'mash-45080.firebasestorage.app',
    measurementId: 'G-KH0KDN2FWY',
  );
}
